name: Build and Run Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install CUDA toolkit
        uses: nvidia/cuda-toolkit-install@v1
        with:
          cuda-version: '11.2'
          username: ${{ secrets.NVIDIA_USERNAME }}
          password: ${{ secrets.NVIDIA_PASSWORD }}
      - name: Compile and run test.cpp
        run: |
          nvcc --extended-lambda test.cpp -o test
          ./test
